### ISSUE TITLE
Doesnt Works for Glyphs 2

### ISSUE THREAD

**Issue by Nevu** [urtd/fontinspector#4]
Hello,
Seems the script doesn't works anymore for Glyphs 2 ... 

Could you fix it?

_________ OUTPUT ___________

Traceback (most recent call last):
  File "fontinspector.py", line 235, in <module>
    isCompatible = g.isCompatible(CurrentFont()[glyph],False)
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 1220, in isCompatible
    selfData = self._getMathData()
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 927, in _getMathData
    self.drawPoints(pen)
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsBase.py", line 1502, in drawPoints
    a.drawPoints(pen)
AttributeError: 'GSAnchor' object has no attribute 'drawPoints'

**Comment by Nevu** [comment]
Hey Ondrej,

I opened a repo with a modified version of this script. I would think this modifications leave aside other font-editors, so I would keep this separately.
