### ISSUE TITLE
Non-ASCII character '\xc3' error

### ISSUE THREAD

**Issue by alexeiva** [urtd/fontinspector#5]
Hi

I am getting this error when I run the script:

```
Start
  File "FontInspector.py", line 6
SyntaxError: Non-ASCII character '\xc3' in file FontInspector.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
End
```

**Comment by Nevu** [comment]
Hi,

you could try my modified version of this great script:
There are also some adjustments for glyphs.

https://github.com/Nevu/ScriptsForGlyphs_Nevu

I look forward for feedback

**Comment by setuptype** [comment]
What version of Python do you have? This should be working in 2.3 and higher.

**Comment by setuptype** [comment]
@Nevu Doesn't seem to be working for me in the current state :/

```
Traceback (most recent call last):
  File "<string>", line 169, in <module>
  File "/Library/Python/2.7/site-packages/robofab/objects/objectsRF.py", line 57, in AllFonts
    raise NotImplementedError
NotImplementedError
```

**Comment by alexeiva** [comment]
@setuptype Python 2.7.12. It used to work fine for me in Glyphs 2.2. Thanks for the script BTW, it's very helpful, and the well-designed. 

@Nevu I will give it a try, thanks.

**Comment by alexeiva** [comment]
@Nevu your version works
@setuptype: seems you need to pull the 'updates for Glyphs 2' from nevu's code.

**Comment by Nevu** [comment]
@setuptype I'm not sure, whether I update some code-lines wich are nessecary for G2.3 or just try to make some smaller design update. Let me know, if this is usefull. THX
